### PR TITLE
Add seed to lfmcmc run function

### PR DESCRIPTION
**Pull request by apulsipher**
Add optional seed parameter to LFMCMC run function to set the rand engine seed

### CODE REVIEW

**Comment by gvegayon** [comment]
Please bump the patch version in `epiworld.hpp` one number up!

**Comment by apulsipher** [comment]
> Please bump the patch version in `epiworld.hpp` one number up!

@gvegayon I bumped the patch version, but see that it is failing the codecov/project check. What is this checking and how do I resolve that?

**Comment by gvegayon** [comment]
> > Please bump the patch version in `epiworld.hpp` one number up!
> 
> @gvegayon I bumped the patch version, but see that it is failing the codecov/project check. What is this checking and how do I resolve that?

Codecov checks for the delta in testing. Since you added a couple of lines, it is complaining that we have relatively less testing than in the master version. It's OK for the moment.

**Comment by gvegayon** [comment]
Oh, also please run the Make command that updates the single header. Thanks!

**Comment by apulsipher** [comment]
> Oh, also please run the Make command that updates the single header. Thanks!

Done

**Review by gvegayon — APPROVED** [review]

**Pull request merged**
